//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoeSuite.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Hotkeys : global::System.Configuration.ApplicationSettingsBase {
        
        private static Hotkeys defaultInstance = ((Hotkeys)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Hotkeys())));
        
        public static Hotkeys Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F1")]
        public global::LowLevelInput.Hooks.VirtualKeyCode Logout {
            get {
                return ((global::LowLevelInput.Hooks.VirtualKeyCode)(this["Logout"]));
            }
            set {
                this["Logout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F12")]
        public global::LowLevelInput.Hooks.VirtualKeyCode OpenSettings {
            get {
                return ((global::LowLevelInput.Hooks.VirtualKeyCode)(this["OpenSettings"]));
            }
            set {
                this["OpenSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F5")]
        public global::LowLevelInput.Hooks.VirtualKeyCode EnterHideout {
            get {
                return ((global::LowLevelInput.Hooks.VirtualKeyCode)(this["EnterHideout"]));
            }
            set {
                this["EnterHideout"] = value;
            }
        }
    }
}
